//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KabiriGam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsForContent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Txt { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Content_Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        public virtual Content Content { get; set; }
    }
}
