//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KabiriGam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsForService
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Txt { get; set; }
        public Nullable<int> Services_Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
