//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KabiriGam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbIrgam : DbContext
    {
        public DbIrgam()
            : base("name=DbIrgam")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AboutUsPage> AboutUsPages { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CommentsForContent> CommentsForContents { get; set; }
        public virtual DbSet<CommentsForProject> CommentsForProjects { get; set; }
        public virtual DbSet<CommentsForService> CommentsForServices { get; set; }
        public virtual DbSet<Contactu> Contactus { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<RequestForOneQuestion> RequestForOneQuestions { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetworks { get; set; }
    
        public virtual int DeleteOneContact(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneContact", idParameter);
        }
    
        public virtual int DeleteOneContent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneContent", idParameter);
        }
    
        public virtual int DeleteOneContentCommen(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneContentCommen", idParameter);
        }
    
        public virtual int DeleteOneProject(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneProject", idParameter);
        }
    
        public virtual int DeleteOneProjectComment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneProjectComment", idParameter);
        }
    
        public virtual int DeleteOneService(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneService", idParameter);
        }
    
        public virtual int DeleteOneServiceComment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOneServiceComment", idParameter);
        }
    
        public virtual int InsertOneCommentForOneContent(string name, string txt, string email, Nullable<int> co_id, Nullable<System.DateTime> date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var co_idParameter = co_id.HasValue ?
                new ObjectParameter("co_id", co_id) :
                new ObjectParameter("co_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneCommentForOneContent", nameParameter, txtParameter, emailParameter, co_idParameter, dateParameter);
        }
    
        public virtual int InsertOneCommentForOneProject(string name, string email, string txt, Nullable<int> proid, Nullable<System.DateTime> date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneCommentForOneProject", nameParameter, emailParameter, txtParameter, proidParameter, dateParameter);
        }
    
        public virtual int InsertOneCommentForOneServices(string name, string email, string txt, Nullable<int> ser_id, Nullable<System.DateTime> date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var ser_idParameter = ser_id.HasValue ?
                new ObjectParameter("ser_id", ser_id) :
                new ObjectParameter("ser_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneCommentForOneServices", nameParameter, emailParameter, txtParameter, ser_idParameter, dateParameter);
        }
    
        public virtual int InsertOneContact(string name, string txt, Nullable<System.DateTime> date, string email)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneContact", nameParameter, txtParameter, dateParameter, emailParameter);
        }
    
        public virtual int insertOneContent(string name, string txt, Nullable<System.DateTime> date, byte[] pic, string shorttxt)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(byte[]));
    
            var shorttxtParameter = shorttxt != null ?
                new ObjectParameter("shorttxt", shorttxt) :
                new ObjectParameter("shorttxt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertOneContent", nameParameter, txtParameter, dateParameter, picParameter, shorttxtParameter);
        }
    
        public virtual int InsertOneProject(string name, string txt, byte[] logo1)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var logo1Parameter = logo1 != null ?
                new ObjectParameter("logo1", logo1) :
                new ObjectParameter("logo1", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneProject", nameParameter, txtParameter, logo1Parameter);
        }
    
        public virtual int InsertOneService(string name, Nullable<System.DateTime> date, string txt, byte[] pic, string showtxt)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(byte[]));
    
            var showtxtParameter = showtxt != null ?
                new ObjectParameter("showtxt", showtxt) :
                new ObjectParameter("showtxt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOneService", nameParameter, dateParameter, txtParameter, picParameter, showtxtParameter);
        }
    
        public virtual ObjectResult<SelectAllCommentForOneServices_Result> SelectAllCommentForOneServices(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllCommentForOneServices_Result>("SelectAllCommentForOneServices", idParameter);
        }
    
        public virtual ObjectResult<SelectAllContents_Result> SelectAllContents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllContents_Result>("SelectAllContents");
        }
    
        public virtual ObjectResult<SelectAllOneContacts_Result> SelectAllOneContacts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllOneContacts_Result>("SelectAllOneContacts");
        }
    
        public virtual ObjectResult<SelectAllOneContentComment_Result> SelectAllOneContentComment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllOneContentComment_Result>("SelectAllOneContentComment", idParameter);
        }
    
        public virtual ObjectResult<SelectAllOneProjectComment_Result> SelectAllOneProjectComment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllOneProjectComment_Result>("SelectAllOneProjectComment", idParameter);
        }
    
        public virtual ObjectResult<SelectAllProjects_Result> SelectAllProjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllProjects_Result>("SelectAllProjects");
        }
    
        public virtual ObjectResult<SelectAllServices_Result> SelectAllServices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllServices_Result>("SelectAllServices");
        }
    
        public virtual ObjectResult<SelectOneContact_Result> SelectOneContact(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOneContact_Result>("SelectOneContact", idParameter);
        }
    
        public virtual ObjectResult<SelectOneContent_Result> SelectOneContent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOneContent_Result>("SelectOneContent", idParameter);
        }
    
        public virtual ObjectResult<SelectOneProject_Result> SelectOneProject(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOneProject_Result>("SelectOneProject", idParameter);
        }
    
        public virtual ObjectResult<SelectOneService_Result> SelectOneService(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOneService_Result>("SelectOneService", idParameter);
        }
    
        public virtual ObjectResult<Selectslider_Result> Selectslider()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Selectslider_Result>("Selectslider");
        }
    
        public virtual int UpdateOneContent(string name, string txt, Nullable<System.DateTime> date, byte[] pic, Nullable<int> id, string shorttxt)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(byte[]));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var shorttxtParameter = shorttxt != null ?
                new ObjectParameter("shorttxt", shorttxt) :
                new ObjectParameter("shorttxt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateOneContent", nameParameter, txtParameter, dateParameter, picParameter, idParameter, shorttxtParameter);
        }
    
        public virtual int UpdateOneProject(string name, string txt, byte[] logo1, Nullable<int> id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var logo1Parameter = logo1 != null ?
                new ObjectParameter("logo1", logo1) :
                new ObjectParameter("logo1", typeof(byte[]));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateOneProject", nameParameter, txtParameter, logo1Parameter, idParameter);
        }
    
        public virtual int UpdateOneService(string name, Nullable<System.DateTime> date, string txt, byte[] pic, Nullable<int> id, string shorttxt)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(byte[]));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var shorttxtParameter = shorttxt != null ?
                new ObjectParameter("shorttxt", shorttxt) :
                new ObjectParameter("shorttxt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateOneService", nameParameter, dateParameter, txtParameter, picParameter, idParameter, shorttxtParameter);
        }
    }
}
